-- Injeção em lote da base massiva de exercícios estruturados
INSERT OR IGNORE INTO exercises (id, name, muscleId, equipment) VALUES
('peito_1', 'Supino Reto com Barra', 'chest', 'barbell'),
('peito_2', 'Supino Reto com Halteres', 'chest', 'dumbbell'),
('peito_3', 'Supino Inclinado com Barra', 'chest', 'barbell'),
('peito_4', 'Supino Inclinado com Halteres', 'chest', 'dumbbell'),
('peito_5', 'Supino Declinado com Barra', 'chest', 'barbell'),
('peito_6', 'Supino Declinado com Halteres', 'chest', 'dumbbell'),
('peito_7', 'Crucifixo Reto com Halteres', 'chest', 'dumbbell'),
('peito_8', 'Crucifixo Inclinado com Halteres', 'chest', 'dumbbell'),
('peito_9', 'Crossover na Polia Alta', 'chest', 'cable'),
('peito_10', 'Crossover na Polia Baixa', 'chest', 'cable'),
('peito_11', 'Peck Deck (Voador / Peitoral Máquina)', 'chest', 'machine'),
('peito_12', 'Supino Vertical na Máquina (Press)', 'chest', 'machine'),
('peito_13', 'Supino Inclinado Articulado (Convergente)', 'chest', 'machine'),
('peito_14', 'Flexão de Braço (Push-up)', 'chest', 'bodyweight'),
('peito_15', 'Paralelas com foco em Peitoral (Dips)', 'chest', 'bodyweight'),

('costas_1', 'Puxada Alta Pronada (Pulldown)', 'back', 'cable'),
('costas_2', 'Puxada Alta com Pegada Supinada', 'back', 'cable'),
('costas_3', 'Puxada Alta Triângulo (Pegada Neutra)', 'back', 'cable'),
('costas_4', 'Remada Baixa na Polia com Triângulo', 'back', 'cable'),
('costas_5', 'Remada Baixa na Polia Unilateral', 'back', 'cable'),
('costas_6', 'Remada Cavalinho (Barra em T)', 'back', 'barbell'),
('costas_7', 'Remada Curvada com Barra Pronada', 'back', 'barbell'),
('costas_8', 'Remada Curvada com Halteres', 'back', 'dumbbell'),
('costas_9', 'Remada Unilateral com Halter (Serrote)', 'back', 'dumbbell'),
('costas_10', 'Remada na Máquina Articulada (Baixa/Média)', 'back', 'machine'),
('costas_11', 'Pulldown na Polia Alta com Barra Reta', 'back', 'cable'),
('costas_12', 'Pullover com Halter', 'back', 'dumbbell'),
('costas_13', 'Levantamento Terra (Deadlift)', 'back', 'barbell'),
('costas_14', 'Barra Fixa Pronada (Pull-up)', 'back', 'bodyweight'),
('costas_15', 'Barra Fixa Supinada (Chin-up)', 'back', 'bodyweight'),
('costas_16', 'Extensão Lombar (Banco Romano)', 'back', 'bodyweight'),

('ombros_1', 'Desenvolvimento com Halteres (Shoulder Press)', 'shoulders', 'dumbbell'),
('ombros_2', 'Desenvolvimento com Barra (Militar)', 'shoulders', 'barbell'),
('ombros_3', 'Desenvolvimento na Máquina', 'shoulders', 'machine'),
('ombros_4', 'Elevação Lateral com Halteres', 'shoulders', 'dumbbell'),
('ombros_5', 'Elevação Lateral na Polia (Unilateral)', 'shoulders', 'cable'),
('ombros_6', 'Elevação Lateral na Máquina', 'shoulders', 'machine'),
('ombros_7', 'Elevação Frontal com Halteres (Alternada)', 'shoulders', 'dumbbell'),
('ombros_8', 'Elevação Frontal com Barra', 'shoulders', 'barbell'),
('ombros_9', 'Elevação Frontal na Polia com Corda', 'shoulders', 'cable'),
('ombros_10', 'Crucifixo Invertido com Halteres (Posterior)', 'shoulders', 'dumbbell'),
('ombros_11', 'Crucifixo Invertido no Pec Deck (Posterior)', 'shoulders', 'machine'),
('ombros_12', 'Crucifixo Invertido na Polia (Face Pull)', 'shoulders', 'cable'),
('ombros_13', 'Encolhimento de Ombros com Halteres (Trapézio)', 'shoulders', 'dumbbell'),
('ombros_14', 'Encolhimento de Ombros com Barra', 'shoulders', 'barbell'),

('bracos_1', 'Rosca Direta com Barra W', 'biceps', 'barbell'),
('bracos_2', 'Rosca Direta com Barra Reta', 'biceps', 'barbell'),
('bracos_3', 'Rosca Alternada com Halteres', 'biceps', 'dumbbell'),
('bracos_4', 'Rosca Inclinada com Halteres (Banco 45°)', 'biceps', 'dumbbell'),
('bracos_5', 'Rosca Concentrada com Halter', 'biceps', 'dumbbell'),
('bracos_6', 'Rosca Scott com Barra W', 'biceps', 'barbell'),
('bracos_7', 'Rosca Scott na Máquina Articulada', 'biceps', 'machine'),
('bracos_8', 'Rosca Direta na Polia Baixa', 'biceps', 'cable'),
('bracos_9', 'Rosca Martelo com Halteres', 'biceps', 'dumbbell'),
('bracos_10', 'Rosca Martelo na Polia com Corda', 'biceps', 'cable'),
('bracos_11', 'Tríceps Pulley com Barra Reta', 'biceps', 'cable'),
('bracos_12', 'Tríceps Pulley com Corda', 'biceps', 'cable'),
('bracos_13', 'Tríceps Pulley Inverso (Pegada Supinada)', 'biceps', 'cable'),
('bracos_14', 'Tríceps Testa com Barra W', 'biceps', 'barbell'),
('bracos_15', 'Tríceps Testa com Halteres', 'biceps', 'dumbbell'),
('bracos_16', 'Tríceps Francês com Halter (Bilateral)', 'biceps', 'dumbbell'),
('bracos_17', 'Tríceps Francês Unilateral na Polia', 'biceps', 'cable'),
('bracos_18', 'Tríceps Coice com Halter (Kickback)', 'biceps', 'dumbbell'),
('bracos_19', 'Mergulho no Banco (Bench Dips)', 'biceps', 'bodyweight'),
('bracos_20', 'Rosca Inversa com Barra (Antebraço)', 'biceps', 'barbell'),
('bracos_21', 'Flexão de Punho com Barra (Antebraço)', 'biceps', 'barbell'),

('pernas_1', 'Agachamento Livre com Barra', 'quads', 'barbell'),
('pernas_2', 'Agachamento Hack (Máquina)', 'quads', 'machine'),
('pernas_3', 'Agachamento Smith (Barra Guiada)', 'quads', 'machine'),
('pernas_4', 'Leg Press 45°', 'quads', 'machine'),
('pernas_5', 'Leg Press Horizontal', 'quads', 'machine'),
('pernas_6', 'Cadeira Extensora', 'quads', 'machine'),
('pernas_7', 'Afundo com Halteres', 'quads', 'dumbbell'),
('pernas_8', 'Passada / Avanço com Halteres (Walking Lunges)', 'quads', 'dumbbell'),
('pernas_9', 'Agachamento Búlgaro com Halteres', 'quads', 'dumbbell'),
('pernas_10', 'Agachamento Goblet com Halter', 'quads', 'dumbbell'),

('posteriores_1', 'Stiff com Barra (Romanian Deadlift)', 'hams', 'barbell'),
('posteriores_2', 'Stiff com Halteres', 'hams', 'dumbbell'),
('posteriores_3', 'Mesa Flexora (Deitado)', 'hams', 'machine'),
('posteriores_4', 'Cadeira Flexora (Sentado)', 'hams', 'machine'),
('posteriores_5', 'Flexora Vertical Unilateral (Em pé)', 'hams', 'machine'),
('posteriores_6', 'Flexão de Pernas com Bola Suíça', 'hams', 'bodyweight'),

('glutes_1', 'Elevação Pélvica com Barra', 'glutes', 'barbell'),
('glutes_2', 'Elevação Pélvica na Máquina Articulada', 'glutes', 'machine'),
('glutes_3', 'Cadeira Abdutora', 'glutes', 'machine'),
('glutes_4', 'Glúteo na Polia Alta (Coice com Caneleira)', 'glutes', 'cable'),
('glutes_5', 'Agachamento Sumô com Halter', 'glutes', 'dumbbell'),

('panturrilha_1', 'Gêmeos em pé na Máquina', 'calves', 'machine'),
('panturrilha_2', 'Gêmeos Sentado (Solear Máquina)', 'calves', 'machine'),
('panturrilha_3', 'Gêmeos no Leg Press 45°', 'calves', 'machine'),
('panturrilha_4', 'Gêmeos em pé Unilateral com Halter', 'calves', 'dumbbell'),

('core_1', 'Abdominal Supra no Solo (Crunch)', 'abs', 'bodyweight'),
('core_2', 'Abdominal Infra no Solo (Elevação de Pernas)', 'abs', 'bodyweight'),
('core_3', 'Abdominal Infra na Barra Fixa (Hanging Leg Raise)', 'abs', 'bodyweight'),
('core_4', 'Abdominal Supra na Polia Alta com Corda', 'abs', 'cable'),
('core_5', 'Abdominal Oblíquo Alternado (Bicicleta)', 'abs', 'bodyweight'),
('core_6', 'Abdominal Oblíquo na Polia (Woodchopper)', 'abs', 'cable'),
('core_7', 'Prancha Isométrica Solo', 'abs', 'bodyweight'),
('core_8', 'Abdominal na Roda (Ab Wheel)', 'abs', 'bodyweight');
